package main

import (
	"any-typeurl-test/contract"
	gogoptypes "github.com/gogo/protobuf/types"
	golangpytpes "github.com/golang/protobuf/ptypes"
)

func main() {
	print("using Go code generated by golang/protobuf\n")
	m := &contract.Message{Greeting: "hello, world"}
	golangAny, err := golangpytpes.MarshalAny(m)
	if err != nil {
		panic(err)
	}
	print("TypeUrl of *any.Any generated by golang/protobuf/ptypes is " + golangAny.TypeUrl + "\n") // prints "type.googleapis.com/Message"
	gogoAny, err := gogoptypes.MarshalAny(m)
	if err != nil {
		panic(err)
	}
	print("TypeUrl of *any.Any generated by gogo/protobuf/ptypes is " + gogoAny.TypeUrl + "\n") // prints "type.googleapis.com/"
}
